INSERT INTO juniors_attendances (student_fk_id, time_in, time_out, status, week_no, updated_by, created_at, updated_at)
VALUES
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NULL, 'in', WEEK(NOW()), NULL, NOW(), NOW()),
  (FLOOR(1 + RAND() * 11), NOW(), NOW(), 'out', WEEK(NOW()), NULL, NOW(), NOW());
